name: lando-mariadb
services:
  defaults:
    type: mariadb
  patch:
    type: mariadb:10.2.21
  custom:
    type: mariadb:10.3
    portforward: true
    creds:
      user: pirog
      password: password
      database: stuff
    config:
      database: config/my.cnf
tooling:
  mysql:
    service: custom
    cmd: mysql -uroot
