name: ${PANTHEON_SITE_NAME}
recipe: pantheon
env_file:
  - .env
config:
  framework: wordpress
  id: ${PANTHEON_SITE_ID}
  site: ${PANTHEON_SITE_NAME}
  xdebug: false
  index: true
  edge: true
  cache: true
