name        : iron-b2
recipe      : pantheon
config      :
  framework : drupal7
  site      : headprotech
  id        : 7361b38c-e1dc-46f7-8945-e65cca0fdad3
  xdebug    : false
  index     : true
  edge      : true
  cache     : true
