name: lando-python
services:
  defaults:
    type: python
    command: python /app/http-server.py
  custom:
    type: python:3.6
    port: 8000
    command: python /app/http-server-custom.py
  customssl:
    type: python
    port: 443
    ssl: true
    command: python /app/https-server.py
  patch:
    type: python:3.5.6
  cli:
    type: python
