name: lando-postgres
services:
  defaults:
    type: postgres:10
  patch:
    type: postgres:9.6.14
  custom:
    type: postgres:11
    portforward: true
    creds:
      database: trouble
    config:
      database: config/mythings.conf
  mimicarecipe:
    type: postgres
    creds:
      user: notpostgres
      database: mimic
      password: 'not empty'
tooling:
  verifydefaults:
    service: defaults
    cmd: psql -U postgres database -c \dt
  verifycustom:
    service: custom
    cmd: psql -U postgres trouble -c \dt
  showmax:
    user: root
    service: custom
    cmd: psql -U postgres -c 'SHOW MAX_FILES_PER_PROCESS;'
  crossconnect:
    service: defaults
    cmd: psql -h custom -U postgres trouble -c \dt
